AWSTemplateFormatVersion: "2010-09-09"

Resources:
Ec2Instance:
 Type: 'AWS::EC2::Instance'
 Properties:
   SecurityGroups:
     - !Ref InstanceSecurityGroup
   KeyName: jenkins
   ImageId: 'ami-059e4057d4518e6bf' # you may need to find out what instance types are available in your region - use https://cloud-images.ubuntu.com/locator/ec2/
InstanceSecurityGroup:
 Type: 'AWS::EC2::SecurityGroup'
 Properties:
   GroupDescription: Enable SSH access via port 22
   SecurityGroupIngress:
     - IpProtocol: tcp
       FromPort: '22'
       ToPort: '22'
       CidrIp: 0.0.0.0/0